# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(539, 366)
        self.gridLayout = QtWidgets.QGridLayout(login)
        self.gridLayout.setObjectName("gridLayout")
        self.labelSurname = QtWidgets.QLabel(login)
        self.labelSurname.setObjectName("labelSurname")
        self.gridLayout.addWidget(self.labelSurname, 0, 0, 1, 1)
        self.lineEditSurname = QtWidgets.QLineEdit(login)
        self.lineEditSurname.setObjectName("lineEditSurname")
        self.gridLayout.addWidget(self.lineEditSurname, 0, 1, 1, 1)
        self.labelName = QtWidgets.QLabel(login)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 1, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(login)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 1, 1, 1, 1)
        self.labelNumGroup = QtWidgets.QLabel(login)
        self.labelNumGroup.setObjectName("labelNumGroup")
        self.gridLayout.addWidget(self.labelNumGroup, 2, 0, 1, 1)
        self.lineEditNumGroup = QtWidgets.QLineEdit(login)
        self.lineEditNumGroup.setObjectName("lineEditNumGroup")
        self.gridLayout.addWidget(self.lineEditNumGroup, 2, 1, 1, 1)
        self.btnSignLab = QtWidgets.QPushButton(login)
        self.btnSignLab.setObjectName("btnSignLab")
        self.gridLayout.addWidget(self.btnSignLab, 3, 1, 1, 1)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Dialog"))
        self.labelSurname.setText(_translate("login", "<html><head/><body><p><span style=\" font-size:16pt;\">Фамилия</span></p></body></html>"))
        self.labelName.setText(_translate("login", "<html><head/><body><p><span style=\" font-size:16pt;\">Имя</span></p></body></html>"))
        self.labelNumGroup.setText(_translate("login", "<html><head/><body><p><span style=\" font-size:16pt;\">Номер группы</span></p></body></html>"))
        self.btnSignLab.setText(_translate("login", "Подписать работу"))


#if __name__ == "__main__":
#    import sys
#    app = QtWidgets.QApplication(sys.argv)
#    login = QtWidgets.QDialog()
 #   ui = Ui_login()
 #   ui.setupUi(login)
#    login.show()
 #   sys.exit(app.exec_())
