# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1328, 854)
        self.formLayout = QtWidgets.QFormLayout(login)
        self.formLayout.setObjectName("formLayout")
        self.labelSurname = QtWidgets.QLabel(login)
        self.labelSurname.setObjectName("labelSurname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSurname)
        self.lineEditSurname = QtWidgets.QLineEdit(login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditSurname.setFont(font)
        self.lineEditSurname.setStyleSheet("background-color: #fffaea;")
        self.lineEditSurname.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditSurname.setMaxLength(25)
        self.lineEditSurname.setObjectName("lineEditSurname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditSurname)
        self.labelName = QtWidgets.QLabel(login)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditName.setFont(font)
        self.lineEditName.setStyleSheet("background-color: #fffaea;")
        self.lineEditName.setMaxLength(25)
        self.lineEditName.setObjectName("lineEditName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditName)
        self.labelNumGroup = QtWidgets.QLabel(login)
        self.labelNumGroup.setObjectName("labelNumGroup")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelNumGroup)
        self.lineEditNumINGroup = QtWidgets.QLineEdit(login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditNumINGroup.setFont(font)
        self.lineEditNumINGroup.setStyleSheet("background-color: #fffaea;")
        self.lineEditNumINGroup.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditNumINGroup.setMaxLength(2)
        self.lineEditNumINGroup.setObjectName("lineEditNumINGroup")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditNumINGroup)
        self.labelGroup = QtWidgets.QLabel(login)
        self.labelGroup.setObjectName("labelGroup")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelGroup)
        self.lineEditGroup = QtWidgets.QLineEdit(login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditGroup.setFont(font)
        self.lineEditGroup.setStyleSheet("background-color: #fffaea;")
        self.lineEditGroup.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditGroup.setMaxLength(15)
        self.lineEditGroup.setObjectName("lineEditGroup")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditGroup)
        self.btnSignLab = QtWidgets.QPushButton(login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSignLab.setFont(font)
        self.btnSignLab.setStyleSheet("background-color: #66e3ff;")
        self.btnSignLab.setObjectName("btnSignLab")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btnSignLab)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Dialog"))
        self.labelSurname.setText(_translate("login", "<html><head/><body><p><span style=\" font-size:16pt;\">Фамилия</span></p></body></html>"))
        self.labelName.setText(_translate("login", "<html><head/><body><p><span style=\" font-size:16pt;\">Имя</span></p></body></html>"))
        self.labelNumGroup.setText(_translate("login", "<html><head/><body><p><span style=\" font-size:16pt;\">Номер по списку в группе</span></p></body></html>"))
        self.labelGroup.setText(_translate("login", "<html><head/><body><p><span style=\" font-size:16pt;\">Группа</span></p></body></html>"))
        self.btnSignLab.setText(_translate("login", "Далее"))

