# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task2CheckForm3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_task2CheckUi(object):
    def setupUi(self, task2CheckForm):
        task2CheckForm.setObjectName("task2CheckForm")
        task2CheckForm.resize(451, 585)
        self.gridLayout = QtWidgets.QGridLayout(task2CheckForm)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(task2CheckForm)
        self.label_4.setMaximumSize(QtCore.QSize(60, 60))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("resources/iconePack/check.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(task2CheckForm)
        self.label_2.setMaximumSize(QtCore.QSize(60, 60))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("resources/iconePack/check.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(task2CheckForm)
        self.label_3.setMaximumSize(QtCore.QSize(60, 60))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("resources/iconePack/check.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.labelConnectionsCount = QtWidgets.QLabel(task2CheckForm)
        self.labelConnectionsCount.setObjectName("labelConnectionsCount")
        self.gridLayout.addWidget(self.labelConnectionsCount, 2, 0, 1, 1)
        self.labelNodesCount = QtWidgets.QLabel(task2CheckForm)
        self.labelNodesCount.setObjectName("labelNodesCount")
        self.gridLayout.addWidget(self.labelNodesCount, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(task2CheckForm)
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/iconePack/check.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.labelSoClose = QtWidgets.QLabel(task2CheckForm)
        self.labelSoClose.setObjectName("labelSoClose")
        self.gridLayout.addWidget(self.labelSoClose, 0, 0, 1, 1)
        self.labelConnectionCross = QtWidgets.QLabel(task2CheckForm)
        self.labelConnectionCross.setObjectName("labelConnectionCross")
        self.gridLayout.addWidget(self.labelConnectionCross, 3, 0, 1, 1)
        self.labelEdgesIntersect = QtWidgets.QLabel(task2CheckForm)
        self.labelEdgesIntersect.setObjectName("labelEdgesIntersect")
        self.gridLayout.addWidget(self.labelEdgesIntersect, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(task2CheckForm)
        self.label_6.setMaximumSize(QtCore.QSize(60, 60))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("resources/iconePack/check.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(task2CheckForm)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 1, 1, 1)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        self.label_2.setMinimumSize(QtCore.QSize(60, 60))
        self.label_3.setMinimumSize(QtCore.QSize(60, 60))
        self.label_4.setMinimumSize(QtCore.QSize(60, 60))
        self.label_6.setMinimumSize(QtCore.QSize(60, 60))

        self.retranslateUi(task2CheckForm)
        QtCore.QMetaObject.connectSlotsByName(task2CheckForm)

    def retranslateUi(self, task2CheckForm):
        _translate = QtCore.QCoreApplication.translate
        task2CheckForm.setWindowTitle(_translate("task2CheckForm", "Проверка"))
        self.labelConnectionsCount.setText(_translate("task2CheckForm", "Верное количество связей"))
        self.labelNodesCount.setText(_translate("task2CheckForm", "Верное количество вершин"))
        self.labelSoClose.setText(_translate("task2CheckForm", "Вершины на достаточном расстоянии"))
        self.labelConnectionCross.setText(_translate("task2CheckForm", "Верные связи"))
        self.labelEdgesIntersect.setText(_translate("task2CheckForm", "Связи не пересекаются"))
        self.pushButton.setText(_translate("task2CheckForm", "Закрыть"))
