# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_first_launch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_first_launch(object):
    def setupUi(self, first_launch):
        first_launch.setObjectName("first_launch")
        first_launch.resize(399, 282)
        first_launch.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(first_launch)
        self.verticalLayout.setContentsMargins(100, 100, 100, 100)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnSearchPathToKey = QtWidgets.QPushButton(first_launch)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnSearchPathToKey.setFont(font)
        self.btnSearchPathToKey.setStyleSheet("background-color: #66e3ff;")
        self.btnSearchPathToKey.setCheckable(True)
        self.btnSearchPathToKey.setObjectName("btnSearchPathToKey")
        self.verticalLayout.addWidget(self.btnSearchPathToKey)

        self.retranslateUi(first_launch)
        QtCore.QMetaObject.connectSlotsByName(first_launch)

    def retranslateUi(self, first_launch):
        _translate = QtCore.QCoreApplication.translate
        first_launch.setWindowTitle(_translate("first_launch", "Регистрация ключа преподавателя в системе"))
        self.btnSearchPathToKey.setText(_translate("first_launch", "Указать путь до\n"
"ключа преподаваьеля\n"
"в файловой системе"))
