# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1751, 1035)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(10, 10, 17, 13)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableTaskVar = QtWidgets.QTableWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableTaskVar.setFont(font)
        self.tableTaskVar.setStyleSheet("background-color: #fffaea;")
        self.tableTaskVar.setObjectName("tableTaskVar")
        self.tableTaskVar.setColumnCount(5)
        self.tableTaskVar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableTaskVar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableTaskVar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableTaskVar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableTaskVar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableTaskVar.setHorizontalHeaderItem(4, item)
        self.tableTaskVar.horizontalHeader().setDefaultSectionSize(350)
        self.verticalLayout.addWidget(self.tableTaskVar)
        self.btnsOkCancle = QtWidgets.QDialogButtonBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnsOkCancle.setFont(font)
        self.btnsOkCancle.setStyleSheet("background-color: #66e3ff;")
        self.btnsOkCancle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnsOkCancle.setObjectName("btnsOkCancle")
        self.verticalLayout.addWidget(self.btnsOkCancle)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableTaskVar.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Шифр работы"))
        item = self.tableTaskVar.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Номер отделения"))
        item = self.tableTaskVar.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Число людей, выполняющих работы"))
        item = self.tableTaskVar.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Продолжительность работ (час)"))
        item = self.tableTaskVar.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Прим."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
