# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources.backGround_rc
import resources.labelMAI_rc


class Ui_startWin(object):
    def setupUi(self, startWin):
        startWin.setObjectName("startWin")
        startWin.resize(1328, 844)
        startWin.setStyleSheet("#startWin{background-image: url(:/newPrefix/backGround.png);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(startWin)
        self.verticalLayout.setContentsMargins(20, 5, 20, 10)
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelWelcome = QtWidgets.QLabel(startWin)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.labelWelcome.setFont(font)
        self.labelWelcome.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.labelWelcome.setLineWidth(5)
        self.labelWelcome.setMidLineWidth(5)
        self.labelWelcome.setObjectName("labelWelcome")
        self.verticalLayout.addWidget(self.labelWelcome)
        self.label = QtWidgets.QLabel(startWin)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("image: url(:/newPrefix/logo_mac_mai-min.png);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.labelSurname = QtWidgets.QLabel(startWin)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.labelSurname.setFont(font)
        self.labelSurname.setStyleSheet("")
        self.labelSurname.setObjectName("labelSurname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSurname)
        self.lineEditSurname = QtWidgets.QLineEdit(startWin)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.lineEditSurname.setFont(font)
        self.lineEditSurname.setStyleSheet("background-color: #fffaea;")
        self.lineEditSurname.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhLatinOnly)
        self.lineEditSurname.setMaxLength(25)
        self.lineEditSurname.setObjectName("lineEditSurname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditSurname)
        self.labelNumGroup = QtWidgets.QLabel(startWin)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.labelNumGroup.setFont(font)
        self.labelNumGroup.setObjectName("labelNumGroup")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelNumGroup)
        self.lineEditNumINGroup = QtWidgets.QLineEdit(startWin)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.lineEditNumINGroup.setFont(font)
        self.lineEditNumINGroup.setStyleSheet("background-color: #fffaea;")
        self.lineEditNumINGroup.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditNumINGroup.setInputMask("")
        self.lineEditNumINGroup.setMaxLength(2)
        self.lineEditNumINGroup.setObjectName("lineEditNumINGroup")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditNumINGroup)
        self.labelGroup = QtWidgets.QLabel(startWin)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.labelGroup.setFont(font)
        self.labelGroup.setObjectName("labelGroup")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelGroup)
        self.lineEditGroup = QtWidgets.QLineEdit(startWin)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.lineEditGroup.setFont(font)
        self.lineEditGroup.setStyleSheet("background-color: #fffaea;")
        self.lineEditGroup.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditGroup.setMaxLength(15)
        self.lineEditGroup.setObjectName("lineEditGroup")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditGroup)
        self.btnDeveloperMode = QtWidgets.QPushButton(startWin)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.btnDeveloperMode.setFont(font)
        self.btnDeveloperMode.setStyleSheet("color: rgb(234, 234, 234);\n"
"background-color: rgb(46, 101, 158);")
        self.btnDeveloperMode.setCheckable(True)
        self.btnDeveloperMode.setObjectName("btnDeveloperMode")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.btnDeveloperMode)
        self.btnSignLab = QtWidgets.QPushButton(startWin)
        self.btnSignLab.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btnSignLab.setFont(font)
        self.btnSignLab.setAutoFillBackground(False)
        self.btnSignLab.setStyleSheet("color: rgb(234, 234, 234);\n"
"background-color: rgb(46, 101, 158);")
        self.btnSignLab.setCheckable(True)
        self.btnSignLab.setDefault(False)
        self.btnSignLab.setFlat(False)
        self.btnSignLab.setObjectName("btnSignLab")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnSignLab)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(startWin)
        QtCore.QMetaObject.connectSlotsByName(startWin)

    def retranslateUi(self, startWin):
        _translate = QtCore.QCoreApplication.translate
        startWin.setWindowTitle(_translate("startWin", "РЕГИСТРАЦИЯ"))
        self.labelWelcome.setText(_translate("startWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; color:#e7e7e7;\">ПРАКТИЧЕСКОЕ ЗАНЯТИЕ № 3</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; color:#e7e7e7;\">ПОСТРОЕНИЕ МЕТОДА СЕТЕВОГО ПЛАНИРОВАНИЯ И УПРАВЛЕНИЯ В </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; color:#e7e7e7;\">ТЕХНОЛОГИЧЕСКИХ ПРОЦЕССАХ ЭКСПЛУАТАЦИИ КОСМИЧЕСКИХ СРЕДСТВ</span></p></body></html>"))
        self.labelSurname.setText(_translate("startWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#e7e7e7;\">Ф.И.О.</span></p></body></html>"))
        self.labelNumGroup.setText(_translate("startWin", "<html><head/><body><p><span style=\" font-size:16pt; color:#e7e7e7;\">ВАРИАНТ</span></p></body></html>"))
        self.labelGroup.setText(_translate("startWin", "<html><head/><body><p><span style=\" font-size:16pt; color:#e7e7e7;\">ВЗВОД</span></p></body></html>"))
        self.btnDeveloperMode.setText(_translate("startWin", "Режим разработчика"))
        self.btnSignLab.setText(_translate("startWin", "Начать работу"))

