# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableTask2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tableTask2Widget(object):
    def setupUi(self, tableTask2Widget):
        tableTask2Widget.setObjectName("tableTask2Widget")
        tableTask2Widget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(tableTask2Widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(tableTask2Widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.tableCheckButton = QtWidgets.QPushButton(tableTask2Widget)
        self.tableCheckButton.setObjectName("tableCheckButton")
        self.verticalLayout.addWidget(self.tableCheckButton)

        self.retranslateUi(tableTask2Widget)
        QtCore.QMetaObject.connectSlotsByName(tableTask2Widget)

    def retranslateUi(self, tableTask2Widget):
        _translate = QtCore.QCoreApplication.translate
        tableTask2Widget.setWindowTitle(_translate("tableTask2Widget", "Form"))
        self.tableCheckButton.setText(_translate("tableTask2Widget", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tableTask2Widget = QtWidgets.QWidget()
    ui = Ui_tableTask2Widget()
    ui.setupUi(tableTask2Widget)
    tableTask2Widget.show()
    sys.exit(app.exec_())
