# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableTask1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tableTask1(object):
    def setupUi(self, tableTask1):
        tableTask1.setObjectName("tableTask1")
        tableTask1.resize(205, 601)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/iconePack/pngwing.com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tableTask1.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(tableTask1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(tableTask1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(tableTask1)
        QtCore.QMetaObject.connectSlotsByName(tableTask1)

    def retranslateUi(self, tableTask1):
        _translate = QtCore.QCoreApplication.translate
        tableTask1.setWindowTitle(_translate("tableTask1", "Шифр работы"))
