# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextTask2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextTask2(object):
    def setupUi(self, TextTask2):
        TextTask2.setObjectName("TextTask2")
        TextTask2.resize(1569, 322)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextTask2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TextTask2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(TextTask2)
        QtCore.QMetaObject.connectSlotsByName(TextTask2)

    def retranslateUi(self, TextTask2):
        _translate = QtCore.QCoreApplication.translate
        TextTask2.setWindowTitle(_translate("TextTask2", "Задание 2"))
        self.label.setText(_translate("TextTask2", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Задание 2</span></p><p><span style=\" font-size:20pt;\"><br/>1. Заполните таблицы ранних и поздних сроков.</span></p><p><span style=\" font-size:20pt;\">2. Заполните количество человек, выполняющих работу. Значения вписывать в квадраты над ребрами.</span></p><p><span style=\" font-size:20pt;\">3. Укажите все критические пути. Используйте инструмент “Критический путь” и кликайте на ЛКМ по вершинам находящимся на критическом пути.</span></p><p><span style=\" font-size:20pt;\"><br/></span></p></body></html>"))
