# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextTask5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextTask5(object):
    def setupUi(self, TextTask5):
        TextTask5.setObjectName("TextTask5")
        TextTask5.resize(621, 208)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextTask5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TextTask5)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(TextTask5)
        QtCore.QMetaObject.connectSlotsByName(TextTask5)

    def retranslateUi(self, TextTask5):
        _translate = QtCore.QCoreApplication.translate
        TextTask5.setWindowTitle(_translate("TextTask5", "Задание 5"))
        self.label.setText(_translate("TextTask5", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Задание 5</span></p><p align=\"center\"><br/></p><p><span style=\" font-size:14pt;\">Построить график занятости личного состава.</span></p></body></html>"))
