# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextTask1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextTask1(object):
    def setupUi(self, TextTask1):
        TextTask1.setObjectName("TextTask1")
        TextTask1.resize(625, 208)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextTask1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TextTask1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(TextTask1)
        QtCore.QMetaObject.connectSlotsByName(TextTask1)

    def retranslateUi(self, TextTask1):
        _translate = QtCore.QCoreApplication.translate
        TextTask1.setWindowTitle(_translate("TextTask1", "Задание 1"))
        self.label.setText(_translate("TextTask1", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Задание 1</span><br/></p><p>Постройте граф, используя таблицу данных.</p><p>Смотри колонку “Шифр работ”.</p></body></html>"))
