# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextTask6.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextTask6(object):
    def setupUi(self, TextTask6):
        TextTask6.setObjectName("TextTask6")
        TextTask6.resize(1013, 208)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextTask6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TextTask6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(TextTask6)
        QtCore.QMetaObject.connectSlotsByName(TextTask6)

    def retranslateUi(self, TextTask6):
        _translate = QtCore.QCoreApplication.translate
        TextTask6.setWindowTitle(_translate("TextTask6", "Задание 6"))
        self.label.setText(_translate("TextTask6", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Задание 6<br/></span></p><p><span style=\" font-size:20pt;\">Это задание является творческим и системой не проверяется.</span></p><p><span style=\" font-size:20pt;\">Вам требуется: передвигая компоненты графа получить максимально выгодный<br/>график занятости личного состава.</span></p></body></html>"))
