# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextTask3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextTask3(object):
    def setupUi(self, TextTask3):
        TextTask3.setObjectName("TextTask3")
        TextTask3.resize(1025, 322)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextTask3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TextTask3)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(TextTask3)
        QtCore.QMetaObject.connectSlotsByName(TextTask3)

    def retranslateUi(self, TextTask3):
        _translate = QtCore.QCoreApplication.translate
        TextTask3.setWindowTitle(_translate("TextTask3", "Условие 3 задания"))
        self.label.setText(_translate("TextTask3", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Размещение сетевого графика на сетке времени в соответствии с ранними сроками наступления событий</span></p><p align=\"center\"><br/></p><p align=\"justify\">1. разместить сетевой график на сетке времени (временном поле)<br/>в соответствии с ранними сроками их наступления; </p><p align=\"justify\">2. расставить правильные продолжительности работ.</p><p align=\"justify\"><br/>Следует обратить внимание на то, что после расположения событий на временной сетке <br/>расстояния между некоторыми событиями могут быть больше, <br/>чем продолжительность работ. Это свидетельствует о том, что такие работы имеют <br/>резерв времени.</p></body></html>"))
