# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextTask2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextTask2(object):
    def setupUi(self, TextTask2):
        TextTask2.setObjectName("TextTask2")
        TextTask2.resize(707, 374)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextTask2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TextTask2)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(TextTask2)
        QtCore.QMetaObject.connectSlotsByName(TextTask2)

    def retranslateUi(self, TextTask2):
        _translate = QtCore.QCoreApplication.translate
        TextTask2.setWindowTitle(_translate("TextTask2", "Задание 2"))
        self.label.setText(_translate("TextTask2", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Расчет ранних и поздних сроков наступления событий,</span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">нахождение критического пути</span><br/></p><p align=\"center\"><br/></p><p align=\"justify\">1. заполнить продолжительности работ;</p><p align=\"justify\">2. рассчитать для каждого события:</p><p align=\"justify\">- ранний срок наступления события;</p><p align=\"justify\">- поздний срок наступления события; </p><p align=\"justify\">3. найти и выделить критический путь (если их несколько, </p><p align=\"justify\">то выделить нужно все критические пути).</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TextTask2 = QtWidgets.QDialog()
    ui = Ui_TextTask2()
    ui.setupUi(TextTask2)
    TextTask2.show()
    sys.exit(app.exec_())
