# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextTask2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextTask2(object):
    def setupUi(self, TextTask2):
        TextTask2.setObjectName("TextTask2")
        TextTask2.resize(622, 208)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextTask2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TextTask2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(TextTask2)
        QtCore.QMetaObject.connectSlotsByName(TextTask2)

    def retranslateUi(self, TextTask2):
        _translate = QtCore.QCoreApplication.translate
        TextTask2.setWindowTitle(_translate("TextTask2", "Задание 2"))
        self.label.setText(_translate("TextTask2", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Задание 2</span></p><p align=\"center\"><br/></p><p><span style=\" font-size:14pt;\">Рассчитать сетевой график в полигональной форме графическим методом.</span></p></body></html>"))
