# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextTask4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextTask4(object):
    def setupUi(self, TextTask4):
        TextTask4.setObjectName("TextTask4")
        TextTask4.resize(1172, 286)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextTask4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TextTask4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(TextTask4)
        QtCore.QMetaObject.connectSlotsByName(TextTask4)

    def retranslateUi(self, TextTask4):
        _translate = QtCore.QCoreApplication.translate
        TextTask4.setWindowTitle(_translate("TextTask4", "Условие 4 задания"))
        self.label.setText(_translate("TextTask4", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Размещение сетевого графика на сетке времени в соответствии с поздними сроками наступления событий</span></p><p align=\"center\"><br/></p><p align=\"justify\"><span style=\" font-size:14pt;\">1. разместить сетевой график на сетке времени (временном поле)<br/>в соответствии с </span><span style=\" font-size:14pt;\">поздними</span><span style=\" font-size:14pt;\"> сроками их наступления; </span></p><p align=\"justify\"><span style=\" font-size:14pt;\">2. расставить правильные продолжительности работ.</span></p><p align=\"justify\"><span style=\" font-size:14pt;\"><br/>Следует обратить внимание на то, что после расположения событий на временной сетке <br/>расстояния между некоторыми событиями могут быть больше, <br/>чем продолжительность работ. Это свидетельствует о том, что такие работы имеют <br/>резерв времени.</span></p></body></html>"))
