# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowTask5.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow5(object):
    def setupUi(self, MainWindow5):
        MainWindow5.setObjectName("MainWindow5")
        MainWindow5.resize(1601, 1253)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        MainWindow5.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/login_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow5.setWindowIcon(icon)
        MainWindow5.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow5)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow5.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow5)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1601, 21))
        self.menuBar.setStyleSheet("background-color: #b8ffc0;")
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow5.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow5)
        self.statusbar.setStyleSheet("background-color: #b8ffc0;")
        self.statusbar.setObjectName("statusbar")
        MainWindow5.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setIconSize(QtCore.QSize(47, 42))
        self.toolBar.setObjectName("toolBar")
        MainWindow5.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionNewFile = QtWidgets.QAction(MainWindow5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/iconePack/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewFile.setIcon(icon1)
        self.actionNewFile.setObjectName("actionNewFile")
        self.actionOpenFile = QtWidgets.QAction(MainWindow5)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/iconePack/write.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenFile.setIcon(icon2)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionSaveFile = QtWidgets.QAction(MainWindow5)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/iconePack/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveFile.setIcon(icon3)
        self.actionSaveFile.setObjectName("actionSaveFile")
        self.actionSaveFileAs = QtWidgets.QAction(MainWindow5)
        self.actionSaveFileAs.setObjectName("actionSaveFileAs")
        self.actionForward = QtWidgets.QAction(MainWindow5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/iconePack/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForward.setIcon(icon4)
        self.actionForward.setObjectName("actionForward")
        self.actionBackward = QtWidgets.QAction(MainWindow5)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/iconePack/reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBackward.setIcon(icon5)
        self.actionBackward.setObjectName("actionBackward")
        self.actionbtnAddSeq = QtWidgets.QAction(MainWindow5)
        self.actionbtnAddSeq.setCheckable(True)
        self.actionbtnAddSeq.setChecked(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/iconePack/add-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnAddSeq.setIcon(icon6)
        self.actionbtnAddSeq.setObjectName("actionbtnAddSeq")
        self.actionbtnRemoveSeq = QtWidgets.QAction(MainWindow5)
        self.actionbtnRemoveSeq.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/iconePack/cross_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnRemoveSeq.setIcon(icon7)
        self.actionbtnRemoveSeq.setObjectName("actionbtnRemoveSeq")
        self.actionbtnMoveNode = QtWidgets.QAction(MainWindow5)
        self.actionbtnMoveNode.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/iconePack/axis_arrow_icon_138909.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnMoveNode.setIcon(icon8)
        font = QtGui.QFont()
        self.actionbtnMoveNode.setFont(font)
        self.actionbtnMoveNode.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionbtnMoveNode.setObjectName("actionbtnMoveNode")
        self.actionbtnConnectNode = QtWidgets.QAction(MainWindow5)
        self.actionbtnConnectNode.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resources/iconePack/file_addArrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnConnectNode.setIcon(icon9)
        self.actionbtnConnectNode.setObjectName("actionbtnConnectNode")
        self.actionbtnInfo = QtWidgets.QAction(MainWindow5)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resources/iconePack/attachment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnInfo.setIcon(icon10)
        self.actionbtnInfo.setObjectName("actionbtnInfo")
        self.actionbtnHome = QtWidgets.QAction(MainWindow5)
        self.actionbtnHome.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("resources/iconePack/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnHome.setIcon(icon11)
        self.actionbtnHome.setObjectName("actionbtnHome")
        self.actionbtnRemoveNodeConnection = QtWidgets.QAction(MainWindow5)
        self.actionbtnRemoveNodeConnection.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("resources/iconePack/arrowRightDel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnRemoveNodeConnection.setIcon(icon12)
        self.actionbtnRemoveNodeConnection.setObjectName("actionbtnRemoveNodeConnection")
        self.actionbtnZoomIn = QtWidgets.QAction(MainWindow5)
        self.actionbtnZoomIn.setCheckable(False)
        self.actionbtnZoomIn.setChecked(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("resources/iconePack/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnZoomIn.setIcon(icon13)
        self.actionbtnZoomIn.setAutoRepeat(True)
        self.actionbtnZoomIn.setObjectName("actionbtnZoomIn")
        self.actionbtnZoomOut = QtWidgets.QAction(MainWindow5)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("resources/iconePack/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnZoomOut.setIcon(icon14)
        self.actionbtnZoomOut.setObjectName("actionbtnZoomOut")
        self.actionHelpTask = QtWidgets.QAction(MainWindow5)
        self.actionHelpTask.setObjectName("actionHelpTask")
        self.actionHelpProgram = QtWidgets.QAction(MainWindow5)
        self.actionHelpProgram.setObjectName("actionHelpProgram")
        self.actionSetting = QtWidgets.QAction(MainWindow5)
        self.actionSetting.setObjectName("actionSetting")
        self.actionbtnCheck = QtWidgets.QAction(MainWindow5)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("resources/iconePack/check-mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnCheck.setIcon(icon15)
        self.actionbtnCheck.setObjectName("actionbtnCheck")
        self.actionbtnDottedConnectNode = QtWidgets.QAction(MainWindow5)
        self.actionbtnDottedConnectNode.setCheckable(True)
        self.actionbtnDottedConnectNode.setEnabled(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("resources/iconePack/arrowsDotted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnDottedConnectNode.setIcon(icon16)
        self.actionbtnDottedConnectNode.setObjectName("actionbtnDottedConnectNode")
        self.actionHelp = QtWidgets.QAction(MainWindow5)
        self.actionHelp.setCheckable(True)
        self.actionHelp.setEnabled(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("resources/iconePack/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon17)
        self.actionHelp.setObjectName("actionHelp")
        self.actionViewTask = QtWidgets.QAction(MainWindow5)
        self.actionViewTask.setObjectName("actionViewTask")
        self.actionbtnZoom100 = QtWidgets.QAction(MainWindow5)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("resources/iconePack/zoom-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbtnZoom100.setIcon(icon18)
        self.actionbtnZoom100.setObjectName("actionbtnZoom100")
        self.menuHelp.addAction(self.actionHelpTask)
        self.menuHelp.addAction(self.actionHelpProgram)
        self.menuHelp.addAction(self.actionViewTask)
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionbtnAddSeq)
        self.toolBar.addAction(self.actionbtnRemoveSeq)
        self.toolBar.addAction(self.actionbtnConnectNode)
        self.toolBar.addAction(self.actionbtnRemoveNodeConnection)
        self.toolBar.addAction(self.actionbtnMoveNode)
        self.toolBar.addAction(self.actionbtnDottedConnectNode)
        # self.toolBar.addSeparator()
        # self.toolBar.addAction(self.actionbtnZoom100)
        # self.toolBar.addAction(self.actionbtnZoomIn)
        # self.toolBar.addAction(self.actionbtnZoomOut)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionbtnCheck)
        self.toolBar.addAction(self.actionbtnInfo)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionbtnHome)

        self.retranslateUi(MainWindow5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow5)

    def retranslateUi(self, MainWindow5):
        _translate = QtCore.QCoreApplication.translate
        MainWindow5.setWindowTitle(_translate("MainWindow5", "Задание 5"))
        self.menuHelp.setTitle(_translate("MainWindow5", "Справка"))
        self.toolBar.setWindowTitle(_translate("MainWindow5", "toolBar"))
        self.actionNewFile.setText(_translate("MainWindow5", "Новый файл"))
        self.actionNewFile.setToolTip(_translate("MainWindow5", "Создать новый файл"))
        self.actionOpenFile.setText(_translate("MainWindow5", "Открыть файл"))
        self.actionSaveFile.setText(_translate("MainWindow5", "Сохранить"))
        self.actionSaveFileAs.setText(_translate("MainWindow5", "Сохранить как"))
        self.actionForward.setText(_translate("MainWindow5", "Вперед        Ctrl+Y"))
        self.actionBackward.setText(_translate("MainWindow5", "Назад          Ctrl+Z"))
        self.actionbtnAddSeq.setText(_translate("MainWindow5", "btnAddNode"))
        self.actionbtnAddSeq.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Добавить последовательность</span></p></body></html>"))
        self.actionbtnRemoveSeq.setText(_translate("MainWindow5", "btnRemoveNode"))
        self.actionbtnRemoveSeq.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Удалить последовательность</span></p></body></html>"))
        self.actionbtnMoveNode.setText(_translate("MainWindow5", "btnMoveNode"))
        self.actionbtnMoveNode.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Переместить вершину</span></p></body></html>"))
        self.actionbtnConnectNode.setText(_translate("MainWindow5", "btnConnectNode"))
        self.actionbtnConnectNode.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Соединить вершины</span></p></body></html>"))
        self.actionbtnInfo.setText(_translate("MainWindow5", "btnInfo"))
        self.actionbtnInfo.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Материалы</span></p></body></html>"))
        self.actionbtnHome.setText(_translate("MainWindow5", "btnHome"))
        self.actionbtnHome.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">В главное окно</span></p></body></html>"))
        self.actionbtnRemoveNodeConnection.setText(_translate("MainWindow5", "btnRemoveNodeСonnection"))
        self.actionbtnRemoveNodeConnection.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Удалить связь</span></p></body></html>"))
        self.actionbtnZoomIn.setText(_translate("MainWindow5", "btnZoomIn"))
        self.actionbtnZoomIn.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Увеличить изображение</span></p></body></html>"))
        self.actionbtnZoomOut.setText(_translate("MainWindow5", "btnZoomOut"))
        self.actionbtnZoomOut.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Уменьшить изображение</span></p></body></html>"))
        self.actionHelpTask.setText(_translate("MainWindow5", "Справка по заданию"))
        self.actionHelpProgram.setText(_translate("MainWindow5", "Справка по программе "))
        self.actionSetting.setText(_translate("MainWindow5", "Настройки программы"))
        self.actionbtnCheck.setText(_translate("MainWindow5", "btnCheck"))
        self.actionbtnCheck.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Проверить задание</span></p></body></html>"))
        self.actionbtnDottedConnectNode.setText(_translate("MainWindow5", "btnDottedConnectNode"))
        self.actionbtnDottedConnectNode.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Расстановка продолжительности работ</span></p></body></html>"))
        self.actionHelp.setText(_translate("MainWindow5", "подсказка"))
        self.actionHelp.setToolTip(_translate("MainWindow5", "<html><head/><body><p><span style=\" font-size:14pt;\">Решение</span></p></body></html>"))
        self.actionViewTask.setText(_translate("MainWindow5", "Задание 5"))
        self.actionbtnZoom100.setText(_translate("MainWindow5", "btnZoom100"))
        self.actionbtnZoom100.setToolTip(_translate("MainWindow5", "Масштабирование к 100%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow5 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow5()
    ui.setupUi(MainWindow5)
    MainWindow5.show()
    sys.exit(app.exec_())

