# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import basedir_paths as bp


class Ui_program_info(object):
    def setupUi(self, program_info):
        program_info.setObjectName("program_info")
        program_info.setFixedSize(600, 180)
        program_info.setStyleSheet("background-color: rgb(175, 211, 255);")
        program_info.setWindowIcon(QtGui.QIcon(bp.join(bp.images_path, "vuc.ico")))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label = QtWidgets.QLabel(program_info)
        self.label.setGeometry(10, -10, 580, 180)
        self.label.setFont(font)
        self.label.setText(" Данная программа была разработана совместным коллективом кафедры\n"
                           "Космических войск Военного учебного центра при МАИ и кафедры №103\n"
                           "Военно-космической академии им А.Ф. Можайского в 2022 году.")


        self.retranslateUi(program_info)
        QtCore.QMetaObject.connectSlotsByName(program_info)

    def retranslateUi(self, program_info):
        _translate = QtCore.QCoreApplication.translate
        program_info.setWindowTitle(_translate("program_info", "О программе"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    program_info = QtWidgets.QWidget()
    ui = Ui_program_info()
    ui.setupUi(program_info)
    program_info.show()
    sys.exit(app.exec_())
